description: |
  You have not provided authentication credentials or they are invalid or have expired.
  Make sure you are sending the `Authorization` header and that it contains a valid bearer token (e.g. `Authorization: Bearer 9q84nv98n`) that has not expired.
