description: Image upload resource.
get:
  description: |
    Retrieve the list of uploaded images.

    If you are authenticated as a user, this will return only the images you uploaded and you will not see the `tokenId` property.
  is: [ any_auth ]
  responses:
    200:
      body:
        application/json:
          example: !include images/get_images_res.json
post:
  description: |
    Upload an image.

    Use the `application/json` content type to upload base64-encoded data.

    Use the `multipart/form-data` content type to upload an image file.
    Send the image file as the `image` field.

    Images cannot be larger than 2MB.
    (When sending base64-encoded image data, the entire JSON payload cannot be larger than 2MB.)

    ## Quota

    If you have reached the image quota (10 by default), your oldest uploaded images will be purged.
  is: [ admin_auth ]
  body:
    application/json:
      example: !include images/post_images_req.json
    multipart/form-data:
      example: |
        Content-Type: multipart/form-data; boundary=AaB03x

        --AaB03x
        Content-Disposition: form-data; name="image"; filename="image.png"
        Content-Type: image/png

        ... contents of image.png ...
        --AaB03x--
  responses:
    201:
      body:
        application/json:
          example: !include images/post_images_res.json
    413:
      description: The uploaded image is too large.
      body:
        text/plain:
          example: The uploaded image is too large (the limit is 2MB).
    415:
      description: The body of the request is in an unsupported format.
      body:
        text/plain:
          example: The request must have content type application/json or multipart/form-data.
    422:
      description: |
        There are errors in the body of the request.

        For the application/json content type, this happens if the "data" property is missing.
        For the multipart/form-data content type, this happens if the "image" field is not set.
      body:
        text/plain:
          example: |
            The "data" property must contain the base64-encoded image data.

            The "image" field is not set.
/{imageId}:
  delete:
    description: |
      Delete an uploaded image.

      If you are authenticated as a user, you must be the one who uploaded the image.
    is: [ any_auth ]
    responses:
      204:
        description: The token and associated images have been successfully deleted.
      404:
        description: No image correspond to the specified ID, or someone else uploaded that image.
        body:
          text/plain:
            example: No image found with ID "682f1d0e-b243-4ed0-9ae2-66e9b4b51193".
