#%RAML 1.0
---
title: qimg API
baseUri: https://comem-qimg.herokuapp.com/api
version: v1
protocols: [HTTPS]
mediaType: application/json

traits:
  any_auth: !include _traits/any_auth.raml
  admin_auth: !include _traits/admin_auth.raml
  user_auth: !include _traits/user_auth.raml

/images: !include images.raml
/tokens: !include tokens.raml
