description: |
  Token management resource.
  The administrator can create tokens that users can use for authentication with the image resources.
get:
  description: |
    Retrieve the list of authentication tokens.
  is: [ admin_auth ]
  responses:
    200:
      body:
        application/json:
          example: !include tokens/get_tokens_res.json
post:
  description: |
    Create a user authentication token.
    This token can be used to upload and list images as a user.

    Tokens are only valid for a limited time.
    You can specify an optional `lifetime` property (in seconds) which defaults to 2,592,000 (30 days).
    It must be at least 1 second and at most 31,536,000 seconds (365 days).

    You can provide an optional `name` property (up to 50 characters long).
  is: [ admin_auth ]
  body:
    application/json:
      example: !include tokens/post_tokens_req.json
  responses:
    201:
      body:
        application/json:
          example: !include tokens/post_tokens_res.json
    422:
      description: |
        There are errors in the body of the request.

        This can happen if

        * the lifetime is not an integer, is less than one, or is more than 365 days;
        * the name is not a string, or longer than 50 characters.
      body:
        text/plain:
          example: |
            The "lifetime" property must be an integer.

            The "lifetime" property must be greater than zero.

            The "lifetime" property must be less than or equal to 31,536,000 (365 days).

            The "name" property must be a string.

            The "name" property must not be longer than 50 characters.
/{tokenId}:
  delete:
    description: |
      Delete an authentication token.

      **All images linked to that user will be purged as well.**
    is: [ admin_auth ]
    responses:
      204:
        description: The token and associated images have been successfully deleted.
      404:
        description: No token correspond to the specified ID.
        body:
          text/plain:
            example: No token found with ID "cf8eb01b-0b39-4355-9226-7a858f5d6172".
