headers:
  Authorization:
    description: |
      The Authorization header must contain a user's or an administrator's bearer token.

      `Authorization: Bearer $BEARER_TOKEN`
    type: string
    required: true
