headers:
  Authorization:
    description: |
      The Authorization header must contain a user's or the administrator's bearer token.

      `Authorization: Bearer $BEARER_TOKEN`
    type: string
    required: true
responses:
  401: !include unauthorized_response.raml
