headers:
  Authorization:
    description: |
      The Authorization header must contain an administrator's bearer token.
      Users are not allowed access to this resource.

      `Authorization: Bearer $BEARER_TOKEN`
    type: string
    required: true
responses: !include auth_responses.raml
